<?php
/**
 * Merge sign-up / legacy rows into `carwashes` safely.
 * Usage: php merge_signups_into_carwashes.php [--dry-run]
 * - --dry-run: do not modify DB, write SQL to migration_apply.sql and conflicts CSV.
 */
require_once __DIR__ . '/../../backend/includes/bootstrap.php';
use App\Classes\Database;

$dryRun = in_array('--dry-run', $argv ?? [], true);

try {
    $db = Database::getInstance();
    $pdo = $db->getPdo();
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    // Detect possible source tables
    $check = $pdo->prepare("SELECT table_name FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name IN ('carwash_profiles','carwash_registrations','carwash_signups')");
    $check->execute();
    $found = $check->fetchAll(PDO::FETCH_COLUMN, 0);

    $sourceTable = null;
    if (in_array('carwash_registrations', $found, true)) $sourceTable = 'carwash_registrations';
    elseif (in_array('carwash_signups', $found, true)) $sourceTable = 'carwash_signups';
    elseif (in_array('carwash_profiles', $found, true)) $sourceTable = 'carwash_profiles';

    if (!$sourceTable) {
        echo "No recognized source table found (checked carwash_profiles, carwash_registrations, carwash_signups)\n";
        exit(1);
    }

    echo "Merging from source: {$sourceTable} (dry-run: " . ($dryRun ? 'yes' : 'no') . ")\n";

    // Ensure audit table exists
    $pdo->exec("CREATE TABLE IF NOT EXISTS carwash_migration_audit (id INT AUTO_INCREMENT PRIMARY KEY, legacy_table VARCHAR(128), legacy_id INT NULL, target_id INT NULL, field_name VARCHAR(128), legacy_value TEXT, target_value TEXT, action VARCHAR(32), resolved TINYINT(1) DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

    // Fetch rows from source
    $rows = $pdo->query("SELECT * FROM {$sourceTable}")->fetchAll(PDO::FETCH_ASSOC);

    if (empty($rows)) {
        echo "No rows found in {$sourceTable}.\n";
        exit(0);
    }

    $applySqlFile = __DIR__ . DIRECTORY_SEPARATOR . 'migration_apply.sql';
    $conflictCsv = __DIR__ . DIRECTORY_SEPARATOR . 'merge_conflicts.csv';
    if ($dryRun) file_put_contents($applySqlFile, "-- Dry-run SQL generated by merge_signups_into_carwashes.php\n\n");

    $conflictFp = fopen($conflictCsv, 'w');
    fputcsv($conflictFp, ['legacy_table','legacy_id','target_id','field','legacy_value','target_value','action']);

    $updated = 0; $inserted = 0; $conflicts = 0;

    foreach ($rows as $r) {
        // Normalize keys from different source formats
        $legacyId = $r['id'] ?? null;
        $userId = $r['user_id'] ?? null;
        $name = $r['business_name'] ?? ($r['name'] ?? ($r['businessName'] ?? null));
        $address = $r['address'] ?? null;
        $phone = $r['contact_phone'] ?? ($r['phone'] ?? null);
        $mobile = $r['mobile_phone'] ?? null;
        $email = $r['contact_email'] ?? ($r['email'] ?? null);
        $logo = $r['featured_image'] ?? ($r['logo_path'] ?? null);
        $social = $r['social_media'] ?? null;
        $working = $r['opening_hours'] ?? ($r['working_hours'] ?? null);
        $services = $r['services'] ?? null;

        // Find existing carwash by user_id OR by name+address
        $foundStmt = $pdo->prepare("SELECT * FROM carwashes WHERE user_id = :uid LIMIT 1");
        $foundStmt->execute(['uid'=>$userId]);
        $existing = $foundStmt->fetch(PDO::FETCH_ASSOC);

        if (!$existing && $name) {
            $foundByName = $pdo->prepare("SELECT * FROM carwashes WHERE name = :name AND (address = :address OR :address = '' OR address IS NULL) LIMIT 1");
            $foundByName->execute(['name'=>$name,'address'=>$address ?? '']);
            $existing = $foundByName->fetch(PDO::FETCH_ASSOC) ?: null;
        }

        if ($existing) {
            $targetId = $existing['id'];
            $toUpdate = [];
            $params = ['id'=>$targetId];

            // Only set fields that are empty in existing
            if (($existing['name'] ?? '') === '' && $name) { $toUpdate[] = 'name = :name'; $params['name'] = $name; }
            if (($existing['address'] ?? '') === '' && $address) { $toUpdate[] = 'address = :address'; $params['address'] = $address; }
            if (($existing['phone'] ?? '') === '' && $phone) { $toUpdate[] = 'phone = :phone'; $params['phone'] = $phone; }
            if (($existing['mobile_phone'] ?? '') === '' && $mobile) { $toUpdate[] = 'mobile_phone = :mobile_phone'; $params['mobile_phone'] = $mobile; }
            if (($existing['email'] ?? '') === '' && $email) { $toUpdate[] = 'email = :email'; $params['email'] = $email; }
            if (($existing['logo_path'] ?? '') === '' && $logo) { $toUpdate[] = 'logo_path = :logo_path'; $params['logo_path'] = $logo; }
            if (($existing['social_media'] ?? '') === '' && $social) { $toUpdate[] = 'social_media = :social_media'; $params['social_media'] = $social; }
            if (($existing['working_hours'] ?? '') === '' && $working) { $toUpdate[] = 'working_hours = :working_hours'; $params['working_hours'] = is_array($working) ? json_encode($working) : $working; }

            // Merge services JSON arrays if available
            if ($services) {
                $existingServices = [];
                if (!empty($existing['services'])) {
                    $decoded = json_decode($existing['services'], true);
                    if (is_array($decoded)) $existingServices = $decoded;
                }
                $incomingServices = is_string($services) ? json_decode($services, true) : $services;
                if (!is_array($incomingServices)) $incomingServices = [];

                // Merge by service name; avoid duplicates
                $merged = $existingServices;
                foreach ($incomingServices as $svc) {
                    $nameKey = $svc['name'] ?? $svc['title'] ?? null;
                    if (!$nameKey) continue;
                    $foundIdx = null;
                    foreach ($merged as $i => $m) {
                        if (($m['name'] ?? $m['title'] ?? '') === $nameKey) { $foundIdx = $i; break; }
                    }
                    if ($foundIdx === null) {
                        $merged[] = $svc;
                    } else {
                        // update price if missing
                        if ((empty($merged[$foundIdx]['price']) || $merged[$foundIdx]['price'] === '') && !empty($svc['price'])) {
                            $merged[$foundIdx]['price'] = $svc['price'];
                        }
                    }
                }
                $mergedJson = json_encode(array_values($merged));
                if ($mergedJson !== ($existing['services'] ?? null)) {
                    $toUpdate[] = 'services = :services'; $params['services'] = $mergedJson;
                }
            }

            if (!empty($toUpdate)) {
                $sql = "UPDATE carwashes SET " . implode(', ', $toUpdate) . " WHERE id = :id";
                if ($dryRun) {
                    file_put_contents($applySqlFile, $sql . ";\n-- params: " . json_encode($params) . "\n\n", FILE_APPEND);
                } else {
                    $pdo->prepare($sql)->execute($params);
                }
                $updated++;
            } else {
                // Nothing to update, but check for conflicts (non-empty differing values)
                $checkFields = ['phone'=>'contact_phone','email'=>'contact_email','name'=>'business_name','address'=>'address'];
                foreach ($checkFields as $t => $scol) {
                    $legacyVal = ${$scol} ?? null;
                    $targetVal = $existing[$t] ?? null;
                    if ($legacyVal && $targetVal && $legacyVal !== $targetVal) {
                        fputcsv($conflictFp, [$sourceTable,$legacyId,$targetId,$t,$legacyVal,$targetVal,'manual_review']);
                        $pdo->prepare("INSERT INTO carwash_migration_audit (legacy_table,legacy_id,target_id,field_name,legacy_value,target_value,action) VALUES (:lt,:lid,:tid,:f,:lv,:tv,'conflict')")->execute([':lt'=>$sourceTable,':lid'=>$legacyId,':tid'=>$targetId,':f'=>$t,':lv'=>$legacyVal,':tv'=>$targetVal]);
                        $conflicts++;
                    }
                }
            }
        } else {
            // Insert new row into carwashes
            $insertCols = ['user_id','name','address','postal_code','city','district','phone','mobile_phone','email','logo_path','social_media','working_hours','services','rating','status','created_at','updated_at'];
            $insertParams = [
                'user_id'=>$userId,
                'name'=>$name,
                'address'=>$address,
                'postal_code'=>$r['postal_code'] ?? null,
                'city'=>$r['city'] ?? null,
                'district'=>$r['district'] ?? null,
                'phone'=>$phone,
                'mobile_phone'=>$mobile,
                'email'=>$email,
                'logo_path'=>$logo,
                'social_media'=>$social,
                'working_hours'=>is_array($working) ? json_encode($working) : $working,
                'services'=>is_array($services) ? json_encode($services) : $services,
                'rating'=>$r['rating'] ?? null,
                'status'=>$r['status'] ?? null,
                'created_at'=>$r['created_at'] ?? date('Y-m-d H:i:s'),
                'updated_at'=>$r['updated_at'] ?? date('Y-m-d H:i:s')
            ];
            $cols = array_keys(array_filter($insertParams, function($v){ return $v !== null; }));
            $placeholders = array_map(function($c){ return ':' . $c; }, $cols);
            $sql = "INSERT INTO carwashes (" . implode(',',$cols) . ") VALUES (" . implode(',',$placeholders) . ")";
            if ($dryRun) {
                file_put_contents($applySqlFile, $sql . ";\n-- params: " . json_encode($insertParams) . "\n\n", FILE_APPEND);
            } else {
                $pdo->prepare($sql)->execute($insertParams);
            }
            $inserted++;
        }
    }

    fclose($conflictFp);

    echo "Merge complete. inserted={$inserted}, updated={$updated}, conflicts={$conflicts}\n";
    if ($dryRun) echo "Dry-run SQL written to {$applySqlFile} and conflicts to {$conflictCsv}\n";

} catch (Throwable $e) {
    echo "Error: " . $e->getMessage() . "\n";
    exit(1);
}

?>
