name: PHP Customer Dashboard Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php-tests:
    name: Run PHP customer dashboard harness
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASS }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_mysql, mbstring, intl

      - name: Install dependencies (composer)
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y default-mysql-client

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            mysql -h${DB_HOST} -P3306 -u${DB_USER} -p"${DB_PASS}" -e 'SELECT 1' && break || sleep 2
          done

      - name: Import test schema
        run: |
          if [ -f database/carwash.sql ]; then
            mysql -h${DB_HOST} -P3306 -u${DB_USER} -p"${DB_PASS}" -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME};" || true
            mysql -h${DB_HOST} -P3306 -u${DB_USER} -p"${DB_PASS}" ${DB_NAME} < database/carwash.sql
          else
            echo "database/carwash.sql not found; skipping import"
          fi

      - name: Create test customer (if script exists)
        run: |
          if [ -f backend/scripts/create_customer.php ]; then
            php backend/scripts/create_customer.php testcust@example.com "TestPass123!" || true
          else
            echo "create_customer.php not found; attempting SQL insert"
            PW=$(php -r 'echo password_hash("TestPass123!", PASSWORD_DEFAULT);')
            mysql -h${DB_HOST} -P3306 -u${DB_USER} -p"${DB_PASS}" ${DB_NAME} -e "INSERT INTO users (email, password, name, role, created_at) VALUES ('testcust@example.com', '${PW}', 'Test Customer', 'customer', NOW())" || true
          fi

      - name: Run harness and capture output
        run: |
          set -o pipefail
          php backend/scripts/run_customer_tests.php testcust@example.com "TestPass123!" 2>&1 | tee harness_output.txt

      - name: Upload harness output (artifact)
        uses: actions/upload-artifact@v3
        with:
          name: harness-output
          path: harness_output.txt

      - name: Check for PHP warnings, errors or failed queries
        run: |
          # Patterns that indicate failure
          PATTERNS='Warning:|Fatal error|Parse error|Notice:|Exception|Query failed|Unknown column|doesn\'t exist'
          if grep -E "$PATTERNS" harness_output.txt; then
            echo "::error::One or more PHP warnings/errors/failed queries detected in harness output.";
            echo "--- Harness output (truncated) ---";
            sed -n '1,200p' harness_output.txt
            exit 1
          else
            echo "No PHP warnings/errors/failed queries detected.";
          fi

      - name: Summary
        run: |
          echo "--- Summary ---";
          echo "Test harness executed: backend/scripts/run_customer_tests.php testcust@example.com \"TestPass123!\"";
          echo "Pages tested: backend/dashboard/customer/index.php, my_bookings.php, process_booking.php, test_db.php";
          echo "Result: PASS - no PHP warnings/errors detected.";
